--CREATE DATABASE PROYECTO 
--USE PROYECTO 

CREATE TABLE USUARIO (
ID_USUARIO INT PRIMARY KEY,
NOMBRE VARCHAR (25),
APELLIDO VARCHAR(25),
USUARIO VARCHAR(30),
PASSWORD VARCHAR (20),
ID_ROL INT,
ACTIVO BIT,
FECHA_CREA DATE,
FECHA_MOD DATE, 
USUARIO_CREA DATE,
USUARIO_MOD DATE,
CODIGO INT
)

ALTER TABLE USUARIO
ADD FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL);

CREATE TABLE ROL(
ID_ROL INT PRIMARY KEY,
NOMBRE VARCHAR (20),
DESCRIPCION VARCHAR (25),
ACTIVO BIT,
USUARIO_CREA DATE,
USUARIO_MOD DATE,
FECHA_CREA DATE,
FECHA_MOD DATE
)

CREATE TABLE MODULO (
ID_MODULO INT PRIMARY KEY,
NOMBRE VARCHAR (25),
DESCRIPCION VARCHAR(25),
PATH VARCHAR (30),
NIVEL INT,
ORDEN INT, 
ID_MODULO_PADRE INT,
ACTIVO BIT,
USUARIO_CREA DATE,
USUARIO_MOD DATE,
FECHA_CREA DATE,
FECHA_MOD DATE
)

CREATE TABLE PERMISO (
ID_PERMISO INT PRIMARY KEY,
ID_MODULO INT,
ID_ROL INT,
ACTIVO BIT,
USUARIO_CREA DATE,
USUARIO_MOD DATE,
FECHA_CREA DATE,
FECHA_MOD DATE
)

ALTER TABLE PERMISO
ADD FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL);

ALTER TABLE PERMISO
ADD FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID_MODULO);