use master
drop database PROYECTO
CREATE DATABASE PROYECTO 
USE PROYECTO 

CREATE TABLE USUARIO (
ID_USUARIO INT PRIMARY KEY,
NOMBRE VARCHAR (25),
APELLIDO VARCHAR(25),
USUARIO VARCHAR(30),
PASSWORD VARCHAR (20),
ID_ROL INT,
ACTIVO INT,
CODIGO INT
)

CREATE TABLE ROL(
ID_ROL INT PRIMARY KEY,
NOMBRE VARCHAR (20),
DESCRIPCION VARCHAR (25),

USUARIO_CREA VARCHAR (20),
USUARIO_MOD VARCHAR (20)
)

CREATE TABLE MODULO (
ID_MODULO INT PRIMARY KEY,
NOMBRE VARCHAR (25),
DESCRIPCION VARCHAR(25),

ID_MODULO_PADRE INT,
ACTIVO INT,
USUARIO_CREA VARCHAR(60),
USUARIO_MOD VARCHAR(50)
)


ALTER TABLE USUARIO
ADD FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL);


CREATE TABLE AREA (
ID_AREA VARCHAR(20) PRIMARY KEY,
DESCRIPCION VARCHAR(50),
ESTADO VARCHAR(20)
)

CREATE TABLE MESA (
ID_AREA VARCHAR(20),
ID_MESA VARCHAR(20) PRIMARY KEY,
DESCRIPCION VARCHAR(50),
ASIENTOS VARCHAR(20),
ID_ESTADO VARCHAR(20)
)

CREATE TABLE PEDIDO (
ID_PEDIDO VARCHAR(20) PRIMARY KEY,
ID_MESA VARCHAR(20),
ID_EMPLEADO VARCHAR(20),
ID_CLIENTE VARCHAR(20),
ID_SUCURSAL VARCHAR(20),
TOTAL VARCHAR(20),
OBSERVACION VARCHAR(20),
ESTADO VARCHAR(20),
FECHA_CREA VARCHAR(20),
USUARIO_CREA VARCHAR(20),
FECHA_MOD VARCHAR(20),
USUARIO_MOD VARCHAR(20)
)

CREATE TABLE DETALLE_PEDIDO (
ID_DETALLE_PEDIDO VARCHAR(20) PRIMARY KEY,
ID_PEDIDO VARCHAR(20),
ID_COMBO VARCHAR(20),
CANTIDAD VARCHAR(20),
PRECIO VARCHAR(20),
TOTAL_LINEA VARCHAR(20),
OBSERVACION VARCHAR(20),
ESTADO VARCHAR(20),
FECHA_CREA VARCHAR(20),
USUARIO_CREA VARCHAR(20),
FECHA_MOD VARCHAR(20),
USUARIO_MOD VARCHAR(20)
)

CREATE TABLE PRODUCTO_COMBO (
ID_COMBO VARCHAR(20) PRIMARY KEY,
ID_TIPO_COMBO VARCHAR(20),
DESCRIPCION VARCHAR(20),
PRECIO VARCHAR(20),
FECHA_CREA VARCHAR(20),
USUARIO_CREA VARCHAR(20),
FECHA_MOD VARCHAR(20),
USUARIO_MOD VARCHAR(20),
ESTADO VARCHAR(20)
)

CREATE TABLE CLIENTE (
ID_CLIENTE VARCHAR(20) PRIMARY KEY,
NOMBRE VARCHAR(50),
NIT VARCHAR(20),
RAZON_SOCIAL VARCHAR(20),
NICKNAME VARCHAR(20),
DIRECCION VARCHAR(20),
TELEFONO VARCHAR(20)
)


